/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myndkdemo_MainActivity */

#ifndef _Included_com_example_myndkdemo_MainActivity
#define _Included_com_example_myndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myndkdemo_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_myndkdemo_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_myndkdemo_MainActivity
 * Method:    mice
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_myndkdemo_MainActivity_mice
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_myndkdemo_MainActivity
 * Method:    aaaa
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_myndkdemo_MainActivity_aaaa
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_myndkdemo_MainActivity
 * Method:    bbbb
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_myndkdemo_MainActivity_bbbb
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
